all:
  hosts:
  children:
    wsl:
      hosts:
        local:
          ansible_port: 22
          ansible_host: 192.168.56.1
          ip: 192.168.56.1
          as_hostname: local
          domains:
            - ip: 192.168.18.22
              domain: vb1.dev.yufei.com
            - ip: 192.168.18.23
              domain: vb2.dev.yufei.com
            - ip: 192.168.18.21
              domain: vb0.dev.yufei.com
            - ip: 192.168.18.18
              domain: gpu0.dev.yufei.com

          netplan_cfg: /etc/netplan/00-installer-config.yaml
          interfaceName: enp4s0
          as_gpu: true

          as_docker_allowed_rw_mounts: /data5/yarn/data,/data5/yarn/logs


          as_redis_dbdir: /data1/redis/data/

          as_hdfs_name_dir: file:///data1/hadoop/hdfs/namenode
          as_hdfs_data_dir: file:///data1/hadoop/hdfs/datanode/
          as_spark_log_dir: /mnt/e/data/spark/logs/
          as_spark_worker_dir: /mnt/e/data/spark/works/
          as_spark_local_dirs: /mnt/e/data/spark/data/
          as_spark_master_host: gpu0.dev.yufei.com
          as_local_dirs: /mnt/e/data/yarn/data
          as_log_dirs: /mnt/e/data/yarn/logs
          as_memory_mb: 80960
          as_cpu_vcores: 200


          app_rootDir: /mnt/e/data/apps/
          app_dataRootDir: /data1/app_data/
          app_logRootDir: /data1/app_logs/
          app_confRootDir: /data1/app_conf/




        vars:
          as_hadoop_master: true
          as_hadoop_slave: true
          as_resourcemanager_address: lcoal.dev.yufei.com
          as_namenode_address: lcoal.dev.yufei.com

    home_master:
      hosts:
        gpu0:
          ansible_port: 22
          ansible_host: 192.168.18.18
          ip: 192.168.18.18
          as_hostname: gpu0.dev.yufei.com
          domains:
            - ip: 192.168.18.22
              domain: vb1.dev.yufei.com
            - ip: 192.168.18.23
              domain: vb2.dev.yufei.com
            - ip: 192.168.18.21
              domain: vb0.dev.yufei.com
            - ip: 192.168.18.18
              domain: gpu0.dev.yufei.com

          netplan_cfg: /etc/netplan/00-installer-config.yaml
          interfaceName: enp4s0
          as_gpu: true

          as_docker_allowed_rw_mounts: /data5/yarn/data,/data5/yarn/logs


          as_redis_dbdir: /data1/redis/data/

          as_hdfs_name_dir: file:///data1/hadoop/hdfs/namenode
          as_hdfs_data_dir: file:///data1/hadoop/hdfs/datanode/
          as_spark_log_dir: /data1/spark/logs/
          as_spark_worker_dir: /data1/spark/works/
          as_spark_local_dirs: /data1/spark/data/
          as_spark_master_host: gpu0.dev.yufei.com
          as_local_dirs: /data1/yarn/data
          as_log_dirs: /data1/yarn/logs
          as_memory_mb: 80960
          as_cpu_vcores: 200


          app_rootDir: /data1/apps/
          app_dataRootDir: /data1/app_data/
          app_logRootDir: /data1/app_logs/
          app_confRootDir: /data1/app_conf/
          es_config:
            node.roles:
              - master
              - data
            vm.max_map_count: 262144

            cluster.name: es
            discovery.seed_hosts:
              - gpu0.dev.yufei.com

            cluster.initial_master_nodes:
              - gpu0.dev.yufei.com
            ES_JAVA_OPTS:
          mongo_config:
            wiredTiger.engineConfig.cacheSizeGB: 10



      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: gpu0.dev.yufei.com
        as_namenode_address: gpu0.dev.yufei.com



    vbs_master:
      hosts:
        vb0:
          ansible_port: 22
          ansible_host: vb0.dev.yufei.com
          ip: 192.168.18.21
          netplan_cfg: /etc/netplan/00-installer-config.yaml
          as_hostname: vb0.dev.yufei.com
          as_gpu: false
          as_hdfs_name_dir: /data/hadoop/hdfs/namenode
          as_docker_allowed_rw_mounts: /data/yarn/data,/data/yarn/logs
          as_local_dirs: /data/yarn/data
          as_log_dirs: /data/yarn/logs
          as_memory_mb: 3300
          as_cpu_vcores: 4
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode

#          app_rootDir: /data/apps/
#          app_dataRootDir: /data/app_data/
#          app_logRootDir: /data/app_logs/
#          app_confRootDir: /data/app_conf/

          #kafka
          kafka_brokerId: 0

          #es
          es_config:
            node.roles:
              - master
            vm.max_map_count: 262144

#            cluster.name: es_vb
#            discovery.seed_hosts:
#              - vb0.dev.yufei.com
#              - vb1.dev.yufei.com
##              - vb2.dev.yufei.com
#
#            cluster.initial_master_nodes:
#              - vb0.dev.yufei.com
#              - vb1.dev.yufei.com
#              - vb2.dev.yufei.com
            ES_JAVA_OPTS:

          #mongo
          mongo_config:
            wiredTiger.engineConfig.cacheSizeGB: 1
#            wiredTiger.inMemory.engineConfig.inMemorySizeGB: 1

          ansible_python_interpreter: /data/apps/miniconda3/bin/python







      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: vb0.dev.yufei.com
        as_namenode_address: vb0.dev.yufei.com
        as_zk_data_dir: /data/zk_data/
    vbs_slaves:
      hosts:
        vb1:
          ansible_port: 22
          ansible_host: vb1.dev.yufei.com
          as_hostname: vb1.dev.yufei.com
          ip: 192.168.18.22
          netplan_cfg: /etc/netplan/00-installer-config.yaml
          as_gpu: false
          as_docker_allowed_rw_mounts: /data/yarn/data,/data/yarn/logs
          as_local_dirs: /data/yarn/data
          as_log_dirs: /data/yarn/logs
          as_memory_mb: 2300
          as_cpu_vcores: 4
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode

          app_rootDir: /data/apps/
          app_dataRootDir: /data/app_data/
          app_logRootDir: /data/app_logs/
          app_confRootDir: /data/app_conf/

          #kafka
          kafka_brokerId: 1
          #es
          es_config:
            node.roles:
              - master
              - data
            vm.max_map_count: 262144

            cluster.name: es_vb
            discovery.seed_hosts:
#              - vb0.dev.yufei.com
              - vb1.dev.yufei.com
#              - vb2.dev.yufei.com

            cluster.initial_master_nodes:
#              - vb0.dev.yufei.com
              - vb1.dev.yufei.com
#              - vb2.dev.yufei.com
            ES_JAVA_OPTS:
        vb2:
          ansible_port: 22
          ansible_host: vb2.dev.yufei.com
          as_hostname: vb2.dev.yufei.com
          ip: 192.168.18.23
          netplan_cfg: /etc/netplan/00-installer-config.yaml
          as_gpu: false
          as_docker_allowed_rw_mounts: /data/yarn/data,/data/yarn/logs
          as_local_dirs: /data/yarn/data
          as_log_dirs: /data/yarn/logs
          as_memory_mb: 2300
          as_cpu_vcores: 4
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode

#          app_rootDir: /data/apps/
#          app_dataRootDir: /data/app_data/
#          app_logRootDir: /data/app_logs/
#          app_confRootDir: /data/app_conf/

          #kafka
          kafka_brokerId: 2
          #es
          es_config:
            vm.max_map_count: 262144

#            cluster.name: es_vb
#            node.roles:
#              - master
#              - data
#            discovery.seed_hosts:
#              - vb0.dev.yufei.com
#              - vb1.dev.yufei.com
#              - vb2.dev.yufei.com

#            cluster.initial_master_nodes:
#              - vb0.dev.yufei.com
#              - vb1.dev.yufei.com
#              - vb2.dev.yufei.com
            ES_JAVA_OPTS:





      vars:
        as_hadoop_master: false
        as_hadoop_slave: true
        as_resourcemanager_address: vb0.dev.yufei.com
        as_namenode_address: vb0.dev.yufei.com



    hadoop_master:
      hosts:
        primary.dev:
          ansible_port: 22
          ansible_host: 172.16.104.220
          ip: 172.16.104.220
          as_hostname: gpu0.dev.yufei.com
          as_gpu: false
          as_hdfs_name_dir: file:///data/hadoop/hdfs/namenode
          as_docker_allowed_rw_mounts: /data5/yarn/data,/data5/yarn/logs
          as_local_dirs: /data5/yarn/data,/data_hadoop_2/yarn/data
          as_log_dirs: /data5/yarn/logs
          as_memory_mb: 80960
          as_cpu_vcores: 200
          as_hdfs_data_dir: file:///data_hadoop_2/hadoop/hdfs/datanode/,file:///data5/hadoop/hdfs/datanode/
          as_redis_dbdir: /data5/redis/data/
          as_spark_log_dir: /data5/spark/logs/
          as_spark_worker_dir: /data5/spark/works/
          as_spark_local_dirs: /data5/spark/data/
          as_spark_master_host: gpu0.dev.yufei.com


          app_rootDir: /data_hadoop_2/apps/
          app_dataRootDir: /data_hadoop_2/app_data/
          app_logRootDir: /data_hadoop_2/app_logs/
          app_confRootDir: /data_hadoop_2/app_conf/
          #es
          es_config:
            node.roles:
              - master
              - data
            vm.max_map_count: 262144

            cluster.name: es_vcg
            discovery.seed_hosts:
              - gpu0.dev.yufei.com

            cluster.initial_master_nodes:
              - gpu0.dev.yufei.com
            ES_JAVA_OPTS: -Xms10g -Xmx10g




#            as_cpu-vcores: 16
#            as_memory-mb: 60960

      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: gpu0.dev.yufei.com
        as_namenode_address: gpu0.dev.yufei.com

    hadoop_slave:
      hosts:
        gpu0.dev:
          ansible_port: 22
          ansible_host: 172.16.108.176
          ip: 172.16.108.176
          as_hostname: gpu0.dev.vcg.com
          as_gpu: true
          as_local_dirs: /data3/yarn/data
          as_log_dirs: /data3/yarn/logs
          as_cpu_vcores: 200
          as_memory_mb: 100960
          as_hdfs_data_dir: file:///data3/hadoop/hdfs/datanode/
          as_spark_log_dir: /data3/spark/logs/
          as_spark_worker_dir: /data3/spark/works/
          as_spark_local_dirs: /data3/spark/data/
          as_spark_master_host: gpu0.dev.yufei.com
          as_docker_allowed_rw_mounts: /data3/yarn/data,/data3/yarn/logs

          app_rootDir: /data3/apps/
          app_dataRootDir: /data3/app_data/
          app_logRootDir: /data3/app_logs/
          app_confRootDir: /data3/app_conf/
          #es
          es_config:
            node.roles:
              - master
              - data
            vm.max_map_count: 262144

            cluster.name: es_vcg
            discovery.seed_hosts:
              - gpu0.dev.vcg.com

            cluster.initial_master_nodes:
              - gpu0.dev.vcg.com
            ES_JAVA_OPTS: -Xms5g -Xmx5g










      vars:
        as_hadoop_master: false
        as_hadoop_slave: true
        as_resourcemanager_address: gpu0.dev.yufei.com
        as_namenode_address: gpu0.dev.yufei.com

    kafka_brokers:
      hosts:
        kafka.dev:
          ansible_port: 22
          ansible_host: 172.16.104.220
          as_hostname: gpu0.dev.yufei.com
          app_rootDir: /data/apps/
          app_dataRootDir: /data/app_data/
          app_logRootDir: /data/app_logs/
          app_confRootDir: /data/app_conf/

      vars:











