---

- name: make sure all related folders present, if present do nothing
  become: yes
  become_user: root
  tags: pulsar_install
  file:
    path: "{{item}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
  loop:
    - "{{app_logRootDir}}{{appName}}/"
    - "{{app_dataRootDir}}{{appName}}/"
    - "{{app_confRootDir}}{{appName}}/"
    - "{{app_rootDir}}{{appName}}/"
- name: upload tgz and unzip to  remote machine
  become: yes
  become_user: root
  tags: pulsar_install
  unarchive:
    src: "{{app_libary_dir}}"
    dest: "{{app_rootDir}}{{appName}}/"
    extra_opts: [--strip-components=1]
#    creates: "{{app_rootDir}}{{appName}}/"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x

- name: start plusar standalone
  become: yes
  tags: pulsar_start
  become_user: "{{op_user}}"
  shell: bash -l -c ' nohup {{app_rootDir}}{{appName}}/bin/pulsar standalone > ./pulsar.out &'
  async: 30
  poll: 2
