---
- name: upload  and unzip to  remote machine
  become: yes
  become_user: root
  tags: kafka_cdc_install
  unarchive:
    src: "{{conn_plugins_dir}}/{{item}}"
    dest: "{{kafka_conn_plugins_path}}"
    owner: "{{op_user}}"
    group: "{{op_user_group}}"
    mode: u=rwx,g=xr,o=x
  with_items: "{{kafka_cdc_cfg['conn-plugins']}}"




- name: start kafka_cdc
  shell:  bash -l -c ' nohup {{app_rootDir}}{{appName}}/bin/connect-distributed.sh {{app_confRootDir}}{{appName}}/connect-distributed.properties > ~/kafka_cdc.log &'
#  when: as_"{{op_user_group}}"_slave
  tags: kafka_cdc_start
  async: 30
  poll: 2