---
java_version: jdk1.8.0_311
jdkFileName: jdk-8u311-linux-x64.tar.gz
java_home_prefix: /usr/local/jdk/
java_home: "{{java_home_prefix}}{{java_version}}"

comm_libarys_path:  /home/comm/software/
jdkPath: "{{comm_libarys_path}}java/{{jdkFileName}}"
goFileName: go1.16.4.linux-amd64.tar.gz
goPath: "{{comm_libarys_path}}go/{{goFileName}}"
go_home_prefix: /usr/local/
go_home: "{{go_home_prefix}}go/"


as_test: "{{java_home}}{{comm_user}}"



# user: hadoop,zhaoyufei,comm
# group: hadoop, sudo,comm
users:
  - username: hadoop
    use_sudo: yes
    groups: hadoop
  - username: hadoop
    use_sudo: yes
    groups: sudo
  - username: zhaoyufei
    use_sudo: yes
    groups: hadoop
  - username: zhaoyufei
    use_sudo: yes
    groups: sudo
  - username: comm
    use_sudo: yes
    groups: sudo
  - username: comm
    use_sudo: yes
    groups: hadoop
  - username: comm
    use_sudo: yes
    groups: comm





#  - username: test2
#    use_sudo: no
#    groups: hadoop




#
#domains:
#  - ip: 172.16.104.220
#    domain: gpu0.dev.yufei.com
#  - ip: 172.16.108.176
#    domain: gpu0.dev.vcg.com
#  - ip: 172.16.237.152
#    domain: gpu1.dev.vcg.com
#
#vbs_domains:
#  - ip: 192.168.18.22
#    domain: vb1.dev.yufei.com
#  - ip: 192.168.18.23
#    domain: vb2.dev.yufei.com
#  - ip: 192.168.18.21
#    domain: vb0.dev.yufei.com







test:
  cluster:
    initial_master_nodes:
      - 127.0.0.1
      - 145.o.o.3
  es_config:
    node.name: node1
    cluster.name: custom-cluster
    cluster.discovery_seed_hosts:
      - 127.0.0.1
      - 128.0.0.1







