---


- name: make sure all related folders present, if present do nothing
  become: yes
  become_user: root
  tags: minio_setup
  file:
    path: "{{item}}"
    owner: root
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
  loop:
    - "{{minio_cfg.dataDir}}/"
- name: config minio-env
  template:
    dest: /etc/profile.d/minio-env.sh
    src: templates/minio-env.sh.j2
    mode: u=rw,g=r,o=r
    owner: root
  become: yes
  become_user: root
  tags:
    - minio_config

- name: copy minio and set file permission
  become: yes
  become_user: root
  tags:
    - minio_setup
  copy:
    src: "{{app_libary_dir}}"
    dest: /usr/local/minio
    mode: a+x
    owner: root



- name: start minio
  become: yes
  become_user: root
  shell: bash -l -c ' nohup /usr/local/minio server {{minio_cfg.dataDir}} --console-address :10000 > ~/minio.log &'
  tags: minio_start