---






app_version: elasticsearch-7.11.2
app_libary_dir: /mnt/d/data/software/elastic/{{app_version}}.tar.gz
es_plugins_dir: /mnt/c/Users/jasstion/OneDrive/software/elastic/plugins
appName: elasticsearch-7.11.2





#kibana:


kibana_package: kibana
kibana_package_state: present


kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml



















